jrincayc/ucblogo-code

graphics.c

One is used to store pointers as well, so needs to be size of pointer.

---

wxMain.cpp
wxTerminal.cpp

Closes #39
Also removes unneeded global nameBufferSize.
Patch from @zigggit

Fixes logo session creating incorrectly named files.

---

wxTerminal.cpp

On OSX Catalina 10.15.6 with wxWidgets 3.0.5 this appears to address Issue #44 - "Can't select/copy text"
Caveat: On my machine, the text is not highlighted during the select; but, does appear to properly populate the clipboard.
Please let me know if there's anything else I need to do for this to be an appropriate PR. I have not tested this on Windows ~or Linux~; but, am happy to do so if that helps.
[EDIT: I setup a VM running Ubuntu Bionic with wxWidgets 3.0.5 and the code change seems to work there as well]

ISSUE-44: Manually convert ASCII buffer into wxString during copy operation so clipboard is populated

---

TextEditor.cpp
wxTerminal.cpp

Resolves #60 
* Explicitly call layout to prevent an issue where the top left corner of the terminal was obscured by the other widgets
* Removed wxWidgets 2.6 workaround which, in wxWidgets 3.0.x, causes the editor to use white for both foreground and background
Test Environments
=
OSX Catalina 10.15.7 w/ wxWidgets 3.0.5
Ubuntu Bionic (18.04.3) w/ wxWidgets 3.0.5
Windows 10 Home (1903) w/ wxWidgets 3.0.5
Context
=
* The changes appear to fix the two issues under OSX without introducing any negative behaviors under Linux or Windows.
* Looking at the commit message of the code on `TextEditor.cpp` (a3598a9b05befc6afc1e23463262cd9b3aa62501), it appears to be a specific workaround for wxWidgets 2.6 on Mac so hopefully safe to remove

ISSUE-60: Fixed a couple of OSX GUI issues.

---

eval.c
tests/UnitTests-Macros.lg
tests/UnitTests.lg

Resolves #43 
* Catch the case of a macro directly invoking `STOP` and return the appropriate error message
* Add unit tests to cover this and neighboring cases
Test Environments
=
OSX Catalina 10.15.7 w/ wxWidgets 3.0.5
Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5
Windows 10 Home (1903) w/ wxWidgets 3.0.5
Test Cases
=
Original issue errors politely:
```logo
? .MACRO AA
>   STOP
> END
AA defined
? AA
Macro returned nothing instead of a list  in AA
[STOP]
? 
```
Error message for similarly problematic function does not change:
```logo
? TO StopFunction
>   STOP
> END
StopFunction defined
? TO CallStopFunction
>   OUTPUT StopFunction
> END
CallStopFunction defined
? CallStopFunction
StopFunction didn't output to OUTPUT  in CallStopFunction
[OUTPUT StopFunction]
? 
```
Behavior of properly …

ISSUE-43: Don't crash when using STOP in macro.

---

coms.c
eval.c
globals.h
logo.h
parse.c
wxGlobals.h
wxMain.cpp
wxTerminal.cpp
wxTurtleGraphics.cpp

Resolves #63 
* Fix bug where a pause character sequence during trace hangs when the CONTINUE command is given
Test Environments
=
OSX Catalina 10.15.7 w/ wxWidgets 3.0.5
Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5
Windows 10 Home (1903) w/ wxWidgets 3.0.5
Caveat
=
The addition of the second parameter flag was the best way I could think of to not change the behavior except in the case of the user input loop. Please let me know if there is a safe approach which is more elegant.

ISSUE-63: Exit getFromWX_2 input loop on pause character sequence.

---

graphics.c
wxTurtleGraphics.cpp

Resolves #47 
On certain window sizes, rounding on the original resize calculation was causing small shifts in the turtle position. On systems where the XOR turtle drawing works, this resulted in ghost turtles. On other systems, there was no ghost turtle; but, post-resize drawn lines could still be misaligned from pre-resize drawn lines.
Additionally, this commit stops the turtle from being drawn in `graphics.c` if it is going to be drawn in wx in order to prevent small gaps in lines if XOR is not supported on the system. As an example, the following is the result of repeatedly typing `fd 6` with a few resizes in the middle on a Linux system that doesn't handle XOR:
Test Environments
=
OSX Catalina 10.15.7 w/ wxWidgets 3.0.5
Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5
Windows 10 Home …

ISSUE-47: Fixed resize bug causing ghost turtle.

---

.github/workflows/ci.yml
tests/UnitTests-Random.lg
tests/UnitTests.lg

Submitting this PR as a proposal - using the unit tests on a few things, I started thinking that CI might be nice. That said, I'm unsure if that's in alignment with the overall project goals. I thought a working example might be a good way to discuss it.
In Action
===
A run triggered by a push to the watched branch:
https://github.com/dmalec/ucblogo-code/actions/runs/358611666
A PR with a change that causes a unit test to fail: https://github.com/dmalec/ucblogo-code/pull/2
*PR View:*
*Details Link View:*
A PR with a change that passes the unit tests: https://github.com/dmalec/ucblogo-code/pull/3
*PR View:*
Overview
===
1. The CI does an `autoreconf/configure/make` cycle and then invokes Logo (wrapped by `xvfb-run`).
2. The results are output to a file which is parsed using `awk` to …

FEATURE-CI: Initial pass at having a CI build.

---

files.c
tests/UnitTests-Files.lg
tests/UnitTests.lg

Resolves #51 
Summary
=
* `OPENWRITE` checks list length before attempting to access buffer size
* `SETWRITE` checks list length before attempting to access buffer size
* When writing to a buffer, allocate one extra byte for null terminator
* Zero out allocated buffer to prevent left over data from appearing
Details
=
The original bug stated that `SETWRITE [WORD]` causes a crash. The root cause was `SETWRITE` assuming a list parameter would have two items and not checking before dereferencing the second item. This crash condition also appeared in `OPENWRITE [WORD]`.
While testing those two fixes, I noticed that, if the data written in Logo is longer than the buffer, it is not properly `NULL` terminated on the C side of things. The following snippet fairly reliably demonstrates the issue: …

ISSUE-51: Improve UX / fix bugs related to char buffer output.

---

globals.h

Mea culpa - I didn't notice the warning message when compiling in my OSX environment.
GitHub's OSX runners view this as a compiler error; so, in addition to wanting to not add a warning, I'm also concerned I may have introduced a compilation problem for others.

HOTFIX ISSUE-69: Added declaration of linemode_on to fix compile error in some OSX environments

---

.github/workflows/cd.yaml
config.h.msys
inno/ucblogo.iss
makefile.msys

To set some context- I'm submitting this PR with the thought it may assist in the overall 6.2 release process. If it's more of a disruption at this point, I can close the PR and work on this as a post-6.2 idea (no worries either way :) ).
I've tried to break down the change into three rough categories below; but, am also going to add a few comments in places where I'm particularly uncertain about the changes I made. To get a sense of what it looks like in action:
https://github.com/dmalec/ucblogo-code/actions/runs/430995787
_(You can view the workflow anonymously; but, do need to be logged into GitHub to download the artifacts)_
**CD features:**
* Builds and caches wxWidgets for three target platforms - Linux, OSX, Windows
* Builds on Linux, producing the PDF, source tar.gz, and source …

CD workflow - build (but do not release) release candidate artifacts.

---

docs/ucblogo.texi

I can retarget to _release_6_2_work_ if that makes more sense or leave as _master_.
Changes:
* Updated `CLEARTEXT` node for new `LINEP` node
* Updated `OBJECT CONSTRUCTORS` node with menu items for `ONEOF`, `SOMETHING`, `KINDOF`
* Moved commas just outside of `@var` tags in object text
Relevant warnings/errors:
```
ucblogo.texi:1491: warning: unlikely character , in @var.
ucblogo.texi:1529: warning: unlikely character , in @var.
ucblogo.texi:5461: warning: unlikely character ( in @var.
ucblogo.texi:5461: warning: unlikely character ) in @var.
ucblogo.texi:5476: warning: unlikely character ( in @var.
ucblogo.texi:5476: warning: unlikely character ) in @var.
ucblogo.texi:5563: warning: unlikely character ( in @var.
ucblogo.texi:5563: warning: unlikely character ) in @var.
ucblogo.texi:5810: …
```

Fix a few errors and warnings in texinfo doc.

---

configure.ac

Handles lack of WX_CONFIG_CHECK better.

If WX_CONFIG_CHECK missing, disable WX.

---

graphics.c
wxTurtleGraphics.h

Resolves #40 
* When `FILLED colornumber` is invoked, make sure the `colornumber` is constrained to the range (original bug)
* Use a signed type for line color so that `SETPENCOLOR rgblist` works as expected (This should fix the bug outlined here: https://sourceforge.net/p/ucblogo/bugs/25/)
* If `SETPENCOLOR` is invoked with a value that produces an error (E.G. negative `colornumber`) don't change anything
* If `SETBACKGROUND` is invoked with a value that produces an error (E.G. negative `colornumber`) don't change anything
The change for `FILLED colornumber` is the one proposed by @zigggit in the bug description. This fixes the reported crashing issue and does not appear to introduce any new issues.
**Test Code**
```
filled -1 [fd 100 rt 90 fd 100]
filled 5 [fd 100 rt 90 fd 100]
filled …
```

ISSUE-40: Fix some issues around color palettes.

---

TextEditor.cpp

Resolves #89 
Resolves #33 
Added a bounds check so that `TextEditor` doesn't attempt to `SetStyle` using a negative starting index.
**OSX**
The root cause of #89 seems to be:
1. Running `EDALL` invokes `TextEditor::Load` which calls `LoadFile` on an empty temp file.
2. As part of the call sequence, this triggers an event.
3. Due to `EVT_TEXT(wxID_ANY, TextEditor::SetThisFont)`, this calls `TextEditor::SetThisFont`.
4. Since the file is empty, `GetLastPosition()-1` is `-1` and the application crashes.
**Linux**
There doesn't seem to be an issue with the initial empty edit; but, deleting the last character in the editor results in the error message discussed in #33.
**Windows**
Appears to be OK with both the previous negative index and the new zero index.
OSX Catalina 10.15.7 w/ wxWidgets …

ISSUE-89: Don't pass a negative index to SetStyle

---

init.c
wrksp.c
wxMain.cpp

Resolves #31 
This change should wrap up the last point on #31 by changing _wxWidgets_ based builds so that `SETEDITOR` changes the behavior of `EDIT`. Specifically:
* wxWidgets builds ignore `EDITOR` env var to preserve default existing behavior
* If `SETEDITOR` is used to set an `editor`, wxWidgets builds will attempt to launch that command for `EDIT`
* If things go awry, `EDIT` will show the attempted command as a file error message
* This doesn't attempt to solve any platform specific issues around invoking an external program (E.G. on OSX, it leaves it up to the user to understand which flags are needed for `open` in order to make it behave well as an editor invocation).
* The implementation prioritizes leaving existing behavior as-is over features (E.G. - fully ignoring the `EDITOR` …

ISSUE-31: Support external editors in wxWidgets builds.

---

docs/ucblogo.texi
files.c

Resolves #54 
When opening the file for the `OPENUPDATE` command, switch from using `a+` to `r+` based on documentation found regarding the two modes. One example:
> Opening a file with append mode (a as the first character in the mode argument) shall cause all subsequent writes to the file to be forced to the then current end-of-file, regardless of intervening calls to fseek().
IEEE Std 1003.1-2017 https://pubs.opengroup.org/onlinepubs/9699919799/
Additionally, advance the file pointer to the end of the file prior to returning. This matches the documentation (and I suspect user expectations) that a file open for updating defaults to appending.
**Test**
```
make "f "TestOverwrite.txt
openwrite :f
setwrite :f
print [this was another test]
close :f
openupdate :f
setwrite :f
setwritepos 2 …
```

ISSUE-54: Fix openupdate file open mode

---

wxMain.cpp

Resolves #95 
Removed an optimization of short sleep durations which looks like it is preventing event processing / TTY updates.
The code snippet in the issue:
```
repeat 100 [print "x wait 1]
```
behaves slightly differently on Windows vs OSX/Linux
On Windows, the `wait` and `print` are interleaved; but, the UI locks up for the duration (E.G. it is not possible to issue a *stop* command via the menu)
On OSX and Linux, the behavior is as described; `print` does not display until the cumulative `wait` time has elapsed. Additionally, the behavior on Windows is also exhibited - the UI goes unresponsive for the cumulative `wait` time.
It looks like this can be replicated for any `wait` from `1` to `6` inclusive. Durations of `7` and above seem to work as expected, with the UI being responsive …

ISSUE-95: Remove special case for short waits to prevent system locking

---

docs/ucblogo.texi
helpfiles/type
term.c
usermanual
wxterm.c

Resolves #96 
It appears that the root cause of the problem is that `TYPE` is being buffered and so the cursor position is not updated prior to the call to `CURSOR`. Therefore, the cursor keeps getting reset to the same position after updating the display of  *accept* / *reject* status. Flushing the buffer prior to reading the cursor appears to fix this.
A bit torn on this one - on the one hand, it seems like reading the `CURSOR` position should have no side effects. That said, I feel like having the position returned by `CURSOR` dependent on internal buffering is a larger surprise when it happens.
While the non-*wxWidgets* implementation don't display the bug in this case, I did update their version of `lcursor` for consistency and did not see any negative side effects during testing. …

ISSUE-96: Flush buffer in CURSOR so position isn't dependent on buffer state

---

files.c

Resolves #97 
The root cause of the crash appears to be a `longjmp` in `unblock_input`:
https://github.com/jrincayc/ucblogo-code/blob/33bc65673ca25089c9acaf8a9eb44bb780686105/main.c#L77-L81
which does not have a corresponding `setjmp`. Working hypothesis is that this results in the value of `iblk_buf` being invalid for the current stack resulting in a crash.
Changing `lreadchar` to call `setjmp` even in *wxWidgets* builds appears to solve the problem.
As well as testing with the case in the original issue, I was able to reproduce the crashing behavior on the current source build using the following:
```
to outer
print inner
end
to inner
output readchar
end
```
Both case were resolved by the moving of `setjmp` and I haven't found any problems this introduces; but, happy to run any tests …

ISSUE-97: Balance calls to setjmp/longjmp regardless of wxWidgets

---

wxTerminal.cpp

Resolves #102 
On OSX, wxWidgets can manage the placement of certain menu items to follow the OSX look and feel without changing the behavior on other platforms. The simplest approach seemed to be changing the _Quit_ menu constant from `Menu_File_Quit` to the wxWidget standard of `wxID_EXIT`.
See: https://wiki.wxwidgets.org/WxMac-specific_topics#Special_Menu_Items
On OSX, the _Quit_ menu item:
* appears under the _UCBLogo_ application menu
* no longer appears under the _File_ menu
* exits the application
* aligns in location with other OSX applications.
On Windows and Ubuntu, the _Quit_ menu item:
* remains under the _File_ menu as before
* continues to work as expected
OSX Catalina (10.15.7) w/ wxWidgets 3.0.5
Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5
Windows 10 Home (1909) w/ wxWidgets …

ISSUE-102: changed quit/exit menu constant to wxWidget standard.

---

Makefile.am
wxCommandHistory.cpp
wxCommandHistory.h
wxTerminal.cpp
wxTerminal.h

Reading through the wx terminal code, I noticed that a feature had been started to remember the current working command during history operations. This seemed like a good idea - without it, an up arrow or down arrow will cause the loss of anything which is being worked on.
There are a few things going on with this change:
* Factored out command history into its own class
* Prevent blank lines from being added to the history
* Remember the working command if one is present
I mulled things over a bit before factoring this out into its own class - my thinking here is that breaking up `wxTerminal.cpp` a bit will help with maintainability and adding features over time. Game to talk this one over more if needed.
Existing functionality with up arrow / down arrow continues to work as expected. If …

Reworked wx terminal command history feature.

---

wrksp.c

Resolves #104 
This avoids an infinite loop on deep copy when the `text` of a procedure is used to define a procedure. The fix is based on @brianharvey 's comment on #104 about needing to untreeify the procedure prior to the deep copy.
The smallest test case I could find which demonstrated the issue is:
```
? define "example [[] [print "first]]
? example
first
? define "example text "example
```
Which led me to placing the untreeify in the `text` procedure.
Game to run any additional tests to make sure this doesn't have any unexpected side effects.
The original case
```
? define "example [[] [print "first] [print "last]]
? example
first
last
? define "example lput [print "new] butlast text "example
? example
first
new
```
Defining a new procedure
```
? define "example [[] [print "first] …
```

ISSUE-104: untreeify procedure when text operator is called.

---

.github/workflows/cd.yaml
.github/workflows/ci.yml

I believe this will address the error on the latest CD build of master:
https://github.com/jrincayc/ucblogo-code/actions/runs/1141287049
Tested on my fork of the repo for both the CI and CD workflows.

Adding step in Linux jobs to update packages prior to installing packages

---

coms.c
wrksp.c

fgets should not be defined until after all includes, otherwise the imported stdio function will be renamed and the help `--more--` prompt will not be read from the wxWidgets window.
Also removes a duplicate include of `ctype.h`

Fix help pagination when using wxWidgets

---

Makefile.am

Resolves #117 
This change is to have the OSX build rename the two special filenames:
- RENAME-GRAVE-ACCENT
- RENAME-NUMBER-SIGN
in `logolib` when building the application.
Without this change, the symptoms described in #117 happen on the OSX builds (but not the Windows or Linux builds).  Once the change has been made, the mentioned commands work as expected:
```
? show `[foo baz ,[bf [a b c]] garply ,@[bf [a b c]]]
[foo baz [b c] garply b c]
```
```
? show cascade 5 [lput # ?] []
[1 2 3 4 5]
```
- OSX Catalina (10.15.7)
I'm unsure if there is a cleaner way to approach using the `install-data-hook` in `logolib/Makefile.am`; however, I could not figure out a way to do that.

ISSUE-117: Correctly rename command files during OSX build

---

wxTerminal.cpp

One possible approach to handling inverted text in wxWidgets builds (both `STANDOUT` and text selection highlighting).
This feels like it could potentially be refined, so I'm going to open it as a draft PR to allow for discussion and further experiments.
* OSX Catalina (10.15.7) w/ wxWidgets 3.0.5
*  Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5 
* Windows 10 Home (1909) w/ wxWidgets 3.0.5

Fix/standardize STANDOUT in wxWidgets builds

---

wxTerminal.cpp
wxTerminal.h

This is one possible approach for handling text selection highlighting. Instead of using `wxINVERT` as a post-process step, it handles selection highlighting by setting the foreground and background when doing the initial draw of the characters. This brings it in line with the new approach for `STANDOUT`. This looks like it should work on OSX, Windows, and Linux.
One point that might particularly be worth discussing further - selection of colors for highlighting. It looks like it's possible to get the system preferred highlight colors using:
```cpp
wxSystemSettings::GetColour(wxSYS_COLOUR_HIGHLIGHTTEXT);
wxSystemSettings::GetColour(wxSYS_COLOUR_HIGHLIGHT);
```
This does carry the risk that the system background doesn't contrast with the current terminal background. This particularly …

Refactor code so selection highlighting does not depend on platform supporting inverted blit mode.

---

wxTerminal.cpp
wxTurtleGraphics.cpp

Resolves #126
This was an interesting bug as there were a few challenges in getting print preview to work on Windows which are Windows specific:
1. The problem that was originally reported seems to be caused by not passing a parent frame to the `wxHtmlEasyPrinting` constructor.
2. With that resolved, the preview was blank and I noticed the turtle graphics preview was also blank. Allowing the event loop to also process idle events appears to resolve this.
3. After a turtle graphics preview (even prior to this change), the key event handling doesn't seem to be properly restored to the terminal. This appears to be resolved by using the logo frame as the parent of the turtle graphics preview.
The final challenge is that the way the text is passed in to the preview appears to cause some …

Issue 126: Print preview on Windows

---

configure.ac

Resolves #129 
* AC_CONFIG_HEADER - this is an obsolete synonym for AC_CONFIG_HEADERS.
https://www.gnu.org/software/automake/manual/1.12/html_node/Obsolete-Macros.html
* AC_HEADER_STDC - this is an obsolete macro, autoconf recommends handling old systems with missing string functions on a case-by-case basis instead of using this macro.
https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Particular-Headers.html
* OSX Catalina (10.15.7) w/ wxWidgets 3.0.5
* Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5 

ISSUE-129: Remove obsolete macros from configure.ac

---

eval.c

resolves #50 
Logo scans to the end of the procedure before raising the error that a `GOTO` references a nonexistent tag. This change:
1. Saves the value of the current line prior to running the code looking for the tag.
2. If the tag is not found, it restores the current line prior to printing an error message.
* OSX Catalina (10.15.7) w/ wxWidgets 3.0.5
* Ubuntu Bionic (18.04.5) w/ wxWidgets 3.0.5 
* Windows 10 Pro (19043.1766) w/ wxWidgets 3.0.5

ISSUE-50: Indicate correct error line when GOTO has a nonexistent tag

---

init.c

Resolves the following three warnings:
```
init.c:710:11: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
logolib = newlib;
^ ~~~~~~
init.c:714:8: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
csls = newcsls;
^ ~~~~~~~
init.c:717:13: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
helpfiles = newhelp;
^ ~~~~~~~
```
Tested that `HELP` can load helpfiles:
```
? HELP "name
NAME value varname                                      (library procedure)
command.  Same as MAKE but with the inputs in reverse order.
```
Tested that library procedures can be called:
```
? NAME 5 …
```

ISSUE-20: Resolving warnings about discarding const qualifier on assignment.

---

eval.c
tests/UnitTests-Control.lg
tests/UnitTests-Macros.lg
tests/UnitTests.lg

Fixes Stopping with repeat

---

.github/workflows/cd.yaml
.github/workflows/ci.yml

Closes #143 
Fixes the following warning during CI/CD:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2
```
Fixes the following warning during CI/CD:
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Fixes issue with CD archiving of Windows installer being sensitive to versions by wildcarding the path:
```
path: inno/ucblogo62setup.exe**
```
changes to:
```
path: …
```

ISSUE-143: Update CI/CD actions from v2 to v3.

---

makefile.msys

Resolves #138 
The Windows build was not renaming the two special character library procedures from:
* RENAME-GRAVE-ACCENT
* RENAME-NUMBER-SIGN
to
*  `` ` ``
*  `#`
This change renames the files during the install so the renamed files can be picked up by inno for packaging.
Without this change, the two commands do not work under Windows (given a clean install of 6.2.2 or a clean install of ucblogo623RCsetup.exe ):
```
? repeat 5 [ print # ]
I don't know how  to #
? print first (cascade 4 "bf [The Continuing Story of Bungalow Bill])
I don't know how  to `  in cascade
[if numberp :cascade.limit [if lessp :cascade.limit 0 [(throw "error (se [cascade doesn't like] :cascade.limit [as input] ))] make "cascade.limit ` [greaterp :template.number , [int :cascade.limit]]]]
```
After the change, the …

ISSUE-138: Rename special character commands during Windows build

---

.github/workflows/cd.yaml

The OSX CD build started producing executables which will not run on OSX 10.<x> systems. My working hypothesis is:
1. GitHub has largely moved the _macOS-latest_ build machines to _macOS-12_ already.
2. OSX 12 needs to have `-mmacosx-version-min` set to 10._x_ for compiling and linking in order to produce an executable for 10._x_.
3. This can be done as a side effect of compiling wxWidgets with `--with-macosx-version-min=10.x` and then using that version of wxWidgets macros during configuration of ucblogo.
4. This can also be done by explicitly setting `-mmacosx-version-min=10.x` prior to compiling logo.
This PR includes two changes:
1. Instead of installing wxWidgets via brew, it installs from the cached copy of wxWidgets. This solves a problem where configure was not finding the …

Fix OSX CD build

---

math.c
tests/UnitTests-Random.lg

Resolves #150 
The `RANDOM` procedure does not check if the first parameter is less than the second parameter on the two input form. This change adds an explicit check and errors if the range is out of order based on the description of the procedure in the manual. It also permits `RANDOM` to accept a range including negative numbers.
Without this change, passing in a higher number first leads to unexpected results:
```
? PRINT (RANDOM 5 3)
825322468
?
```
After making this change, passing in a higher number will produce an error:
```
? PRINT (RANDOM 5 6)
6
? PRINT (RANDOM 6 5)
RANDOM doesn't like [6 5] as input
```
Which is equivalent to passing a negative number to the single input form:
```
? PRINT RANDOM 10
9
? PRINT RANDOM -10
RANDOM doesn't like -10 as input
```
This change also …

ISSUE-150: Validate RANDOM range input has the smaller number first

---

wrksp.c
xgraphics.h

Implicit funciton declarations were removed from C99, and future compilers may not support them by default because they are a type safety hazard.
This commit fixes ucblogo for the Fedora build configure, so it will continue to build with such future compilers.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

Avoid more implicit function declarations

---

wrksp.c

Fix bug with including sys/wait.h in windows.

Move wait include to else of windows.

---

.github/workflows/cd.yaml

Resolves #158 
On the GitHub MacOS runners, it looks like the installation of `brew` includes libraries which get picked up during the `wxWidgets` build. This creates a dependency for the UCBLogo binary on the `brew` installed libraries being present at runtime.
This change configures `wxWidgets` to use its `builtin` versions for `libpng` and `libjpeg` and configures it to build without `libtiff` entirely. In my first attempt, I configured `libtiff` as `builtin` but that triggered another link to a `brew` library which doesn't appear to have a `builtin` option :(
It is possible we can just compile all image libraries as `without` - willing to try that and see if there are any problems.
Ran UCBLogo and made sure things that might have image dependencies (such as printing) continued to work …

ISSUE-158: Configure wxWidgets to avoid linking to brew installed libraries

---

.github/workflows/cd.yaml

Adds `--with-regex=builtin` to CD build for wxWidgets on OSX to prevent dynamic linking to the homebrew installed library on the GitHub action runners. Similar to issue #158  and #161
* OSX Catalina (10.15.7) w/ wxWidgets 3.2.2.1 on Intel Core i7
* OSX Ventura (13.2.1) w/ Rosetta w/ wxWidgets 3.2.2.1 on Apple M2

Configure wxWidgets OSX build to avoid linking to brew installed regex library

---

TextEditor.cpp

Resolves #72 
Resolves #162 
OSX provides smart quotes by default systemwide. Under wxWidgets 3.0.x, there does not appear to be a clear approach to disabling this. Under wxWidgets 3.2.x, it is possible to selectively override the systemwide setting on a per text control basis.
Used the test plan outlined in issue #72 and verified that:
1. On OSX w/ wxWidgets 3.2.x, the text control no longer does smart quote substitution regardless of the systemwide setting.
2. In other cases, the behavior remains the same as it was previously.
* OSX Catalina (10.15.7) w/ wxWidgets 3.0.5
* OSX Catalina (10.15.7) w/ wxWidgets 3.2.2.1
* Windows 10 Pro (19045.2364) w/ wxWidgets 3.2.2.1
* Ubuntu Jammy (22.04) w/ wxWidgets 3.0.5
* Ubuntu Kinetic (22.10) w/ wxWidgets 3.2.0

ISSUE-72: On OSX, disable smart quotes in the editor.

---

wxTerminal.cpp

These need to be handled by wxMenuBar.
Closes #172

Don't handle control and alt commands in terminal.

---

logo.h

This fixes one of the problems in #176 by using SIG_TAKES_ARG for unix.

Define SIG_TAKES_ARG in unix.

---

term.c
xgraphics.c
xgraphics.h

Issue 176 alt

---

.github/workflows/cd.yaml
coms.c

Fixed a few things preventing the CD pipeline from running successfully.
Relatively small tweaks to the way wxWidgets is installed on the build node:
1. Using `sudo` now appears to be required.
2. The homebrew install of `autoconf` needs to have the wxWidgets m4 file manually installed. 
Windows build nodes now provide Inno 6.3.3 as part of the default set of tools. 6.1.2 now causes some instability, so removing this and just using the provided version which seems to work fine.
The Windows build nodes had been treating the appearance of `sleep` in the C code as a warning; but, now seem to treat this as an error. There should be no change in runtime behavior since the `sleep` appears after a `return` statement in wxWidgets builds of the code; but, the change in macros should prevent the …

Fix CD pipeline builds for OSX and Windows

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml

I believe this fixes the last of the v3 -> v4 updates on the pipeline actions and fixes warnings like the following during pipeline execution:
```
Build wxWidgets for OSX
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

Updated remaining pipeline action versions from v3 to v4

---

Makefile.am
configure.ac
logo.h
wxterm.c

These are a bunch of minor patches from updating the Debian package.
The most important is to support GCC-14 and recent glibc.
The others are minor but inoffensive, things like cleaning up the generated `makehelp` binary or making it easier to disable use of the wx library (even though the underlying C code to support that configuration has rotted away.)

misc fixes and updates

---

.github/workflows/cd.yaml

This MR follows up on #186 to address the CD build for versions of OSX prior to 11. CD now builds two version of wxWidgets and two versions of Logo for OSX, using matrix builds to target x86 and ARM. It then adds a stage which takes the individual platform builds of OSX Logo and combines them into a universal binary build.
Size - this does result in a larger application file; I think there may be value in checking what can be disabled in the wxWidgets build without impacting the parts of wxWidgets used by UCB Logo.
Duplicate build logic - I'd like to not replicate the portion of the Makefile which builds the DMG into the CD file; but, I ran into some challenges in solving that and would like to mull some more. My thinking is that, in the meantime, this change will restore CD to working …

Change OSX CD to build a universal binary 

---

coms.c
configure.ac

Use `gettimeofday()` in preference to `time()` in `TIME` word to support microsecond resolution.
Previously this only happened on the `__APPLE__` platform, which is great, but all modern systems should support this function, and we can test it with autoconf to support ancient systems that only have `time()`, if any still exist.
So basically this just adds the autoconf test and changes `__APPLE__` to `HAVE_GETTIMEOFDAY`
This is useful for profiling logo code, E.G.
```
? PO "TIMEIT
TO TIMEIT :INSTRUCTIONS
LOCALMAKE "T1 TIME
RUN :INSTRUCTIONS
OP TIME - :T1
END
? PR TIMEIT [REPEAT 100000 [IGNORE 1 + 1]]
0.467458009719849
```
my python might be showing

Change TIME word to use gettimeofday if available

---

globals.h
intern.c

Does a partial GC before constructing new case objects to ensure there are enough free nodes to finish construction and add it to a root node before the GC runs again.
Case objects must be marked twice so if the GC runs after a new case is allocated but before it is added to the hash table AND a root AND the pointer isn't found on the stack, eg because it was optimized out, then the GC may free the cases.
I was concerned this would have a negative performance impact...
~~It actually improved unit test performance by 10-20%.~~
And it does. It's way slow. I'm not sure how I produced the "improvement". 
So we probably want to find a more performant fix.

Fix race between GC and case object construction

---

wxTerminal.cpp

Enable AltGr in wxTerminal.
